sonar.projectKey=devops-trial
sonar.projectName=devops-trial
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqp_69175203c537742d67e78bae16cf794d39f0d237 
